version: "3.9"
networks:
  default:
    name: laravel_project
services:
  server:
    # image: 'nginx:stable-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    restart: unless-stopped
    ports:
      - "8089:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - database_cluster
      - laravel_project
    container_name: laravel_project_server
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    container_name: php_parametros_server
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - 8088:9000
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
