version: "3.9"
networks:
  database_cluster:
services:
  mysql:
    image: mysql:8.0.1
    restart: unless-stopped
    tty: true
    container_name: mysql_cluster
    env_file:
      - ./env/mysql.env
    ports:
      - 3306:3306
    networks:
      - database_cluster
    volumes:
      - /opt/mysql_data_cluster:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: phpmyadmin_cluster
    depends_on:
      - mysql
    ports:
      - '8890:80'
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=secret
    networks:
      - database_cluster
